console.log("=========================================");
console.log("STARTING ARRAY EXPR MIXIN TESTS...");
console.log("=========================================");

import "./agg.test";
import "./all.test";
import "./any.test";
import "./argMax.test";
import "./argMin.test";
import "./contains.test";
import "./containsAll.test";
import "./containsAny.test";
import "./countMatches.test";
import "./eval.test";
import "./explode.test";
import "./filter.test";
import "./first.test";
import "./gather.test";
import "./gatherEvery.test";
import "./get.test";
import "./join.test";
import "./last.test";
import "./len.test";
import "./lengths.test";
import "./max.test";
import "./mean.test";
import "./median.test";
import "./min.test";
import "./mode.test";
import "./nUnique.test";
import "./reverse.test";
import "./shift.test";
import "./slice.test";
import "./sort.test";
import "./splice.test";
import "./std.test";
import "./sum.test";
import "./toStruct.test";
import "./unique.test";
import "./variance.test";

console.log("✓ All ArrayExpr tests passed successfully!");
