console.log("=========================================");
console.log("STARTING STRING EXPR MIXIN TESTS...");
console.log("=========================================");

import "./concat.test";
import "./contains.test";
import "./containsAny.test";
import "./countMatches.test";
import "./decode.test";
import "./decodeUriComponent.test";
import "./encode.test";
import "./encodeUriComponent.test";
import "./endsWith.test";
import "./escapeRegex.test";
import "./explode.test";
import "./extract.test";
import "./extractAll.test";
import "./extractGroups.test";
import "./extractMany.test";
import "./find.test";
import "./findMany.test";
import "./head.test";
import "./join.test";
import "./jsonDecode.test";
import "./jsonPathMatch.test";
import "./len.test";
import "./lenBytes.test";
import "./lenChars.test";
import "./lower.test";
import "./lpad.test";
import "./normalize.test";
import "./padEnd.test";
import "./padStart.test";
import "./replace.test";
import "./replaceAll.test";
import "./replaceMany.test";
import "./reverse.test";
import "./rpad.test";
import "./slice.test";
import "./split.test";
import "./startsWith.test";
import "./stripChars.test";
import "./stripCharsEnd.test";
import "./stripCharsStart.test";
import "./stripPrefix.test";
import "./stripSuffix.test";
import "./strptime.test";
import "./tail.test";
import "./toCamelCase.test";
import "./toDate.test";
import "./toDatetime.test";
import "./toDecimal.test";
import "./toInteger.test";
import "./toKebabCase.test";
import "./toLowerCase.test";
import "./toPascalCase.test";
import "./toSnakeCase.test";
import "./toTime.test";
import "./toTitleCase.test";
import "./toUpperCase.test";
import "./upper.test";
import "./zfill.test";

console.log("✓ All StringExpr tests passed successfully!");
